### ISSUE TITLE
Wrong namspace is used for the subpart-filter classes

### ISSUE THREAD

**Issue by guelzow** [aimeos/ai-client-html#101]
Hi everyone.

With the configuration:
client/html/catalog/filter/search/standard/subparts
you can add additional search classes to the search.

The AI-Client provides some of them.
When you use this configuration, the following classes are uses
\Aimeos\Client\Html\Catalog\Filter\Search\\...\Standard
(The dots are filled with the value from the configuration.)

Sadly, the provided classes are not part of this namespace, resulting in an error message, that the classes are not found.

Possible solution:
[Here](https://github.com/aimeos/ai-client-html/blob/master/client/html/src/Client/Html/Catalog/Filter/Search/Standard.php#L188), the wrong namespace is used.
Changing it from
```php
return $this->createSubClient( 'catalog/filter/search/' . $type, $name );
```
to
```php
return $this->createSubClient( 'catalog/filter/' . $type, $name );
```
allows the AI-Client to find the classes.

Alternative solution:
Move the provided classes to the right namespace.

Tobi

Edit: Fixed a typo in the namespace above.

**Comment by aimeos** [comment]
Does your new subpart for catalog/filter/search has this namespace?
```
\Aimeos\Client\Html\Catalog\Filter\Search\<subpart-name>\Standard
```
If you want to add a subpart to catalog/filter instead, the namespace must be:
```
\Aimeos\Client\Html\Catalog\Filter\<subpart-name>\Standard
```
and the configuration `client/html/catalog/filter/standard/subparts` is used

**Comment by guelzow** [comment]
I do not use new subparts. I use the ones provided by the AI-Client, with the provided template files.

```php
return [
    'html' => [
        'catalog' => [
            'filter' => [
                'search' => [
                    'standard' => [
                        'subparts' => [
                            'attribute',
                            'supplier',
                            'tree'
                        ]
                    ]
                ],
                'attribute' => [
                    'domains' => [],
                    'types-oneof' => [],
                    'types-option' => []
                ]
            ]
        ]
    ],
];
```

**Comment by guelzow** [comment]
> and the `configuration client/html/catalog/filter/standard/subparts` is used

Then there is another bug:
[Here](https://github.com/aimeos/ai-client-html/blob/master/client/html/src/Client/Html/Catalog/Filter/Search/Standard.php#L58) the configuration `client/html/catalog/filter/search/standard/subparts` is used.

**Comment by aimeos** [comment]
The code is OK but your configuration is wrong. The attribute, supplier and tree subparts are below `catalog/filter/standard/subparts`, not `catalog/filter/search/standard/subparts`:
```
return [
    'html' => [
        'catalog' => [
            'filter' => [
                    'standard' => [
                        'subparts' => [
                            'attribute',
                            'supplier',
                            'tree'
                        ]
                    ],
                'attribute' => [
                    'domains' => [],
                    'types-oneof' => [],
                    'types-option' => []
                ]
            ]
        ]
    ],
];
```

**Comment by guelzow** [comment]
That was actually my first try. If I use the provided configuration above, the search form does not render the search fields for the attributes.

When the search form is rendered (without results), is uses the following configuration:
```php
private $subPartPath = 'client/html/catalog/filter/search/standard/subparts';
```
as can be seen [here](https://github.com/aimeos/ai-client-html/blob/master/client/html/src/Client/Html/Catalog/Filter/Search/Standard.php#L58).

Without it, the subparts [here](https://github.com/aimeos/ai-client-html/blob/master/client/html/templates/catalog/filter/body-standard.php#L106) are empty:
```php
<?= $this->block()->get( 'catalog/filter/tree' ); ?>
<?= $this->block()->get( 'catalog/filter/price' ); ?>
<?= $this->block()->get( 'catalog/filter/supplier' ); ?>
<?= $this->block()->get( 'catalog/filter/attribute' ); ?>
```
But when I use my configuration from above, these subparts get filled.

**Comment by aimeos** [comment]
Your previous configuration is definitively wrong. The catalog/filter/search subpart is added here:
https://github.com/aimeos/ai-client-html/blob/master/client/html/templates/catalog/filter/body-standard.php#L105
Check, if the HTML code is there and if it's a CSS issue.

**Comment by guelzow** [comment]
> Check, if the HTML code is there and if it's a CSS issue.

Sorry, no it's not a display issue.

**What is happening in the code**
The configuration path for these subparts is defined here:
https://github.com/aimeos/ai-client-html/blob/master/client/html/src/Client/Html/Catalog/Filter/Search/Standard.php#L58
```php
private $subPartPath = 'client/html/catalog/filter/search/standard/subparts';
```
The 'search' part is in there.

The configuration is then used here:
https://github.com/aimeos/ai-client-html/blob/master/client/html/src/Client/Html/Catalog/Filter/Search/Standard.php#L199
```php
return $this->getContext()->getConfig()->get( $this->subPartPath, $this->subPartNames );
````
The classes are then created in the base class, with the namespace configuration from here:
https://github.com/aimeos/ai-client-html/blob/master/client/html/src/Client/Html/Catalog/Filter/Search/Standard.php#L188
```php
return $this->createSubClient( 'catalog/filter/search/' . $type, $name );
```
With the search part in them.

The provided classes are in the namespace
```php
namespace Aimeos\Client\Html\Catalog\Filter\Attribute
```
Without the search part.

------------------------------------------

**Summary**
The configuration without the 'search' part is not used.
The configuration **with** the search part tries to create classes **with** the search part.
The provided classes
- `Aimeos\Client\Html\Catalog\Filter\Tree\Standard`
- `Aimeos\Client\Html\Catalog\Filter\Supplier\Standard`
- `Aimeos\Client\Html\Catalog\Filter\Price\Standard`
- `Aimeos\Client\Html\Catalog\Filter\Attribute\Standard`

do not contain the search part in their namespace.

And when I use the configuration with the search part, I get an error:
`Class "\Aimeos\Client\Html\Catalog\Filter\Search\Attribute\Standard" not available`

------------------------------------------

**Our workaround**
We use the configuration with the search part.
And we provide the classes in the namespace with the search part, which extend the original classes.

Heh, explaining this kind of thing is rather hard in a ticket system.    ;-)

**Comment by guelzow** [comment]
Sorry, was a misunderstanding on my part . . .
