### ISSUE TITLE
Review rating does not correctly math

### ISSUE THREAD

**Issue by Dinver** [aimeos/ai-client-html#102]
version 2020.10.x-dev

There is 2 review:
1. rating 5
2. rating 3

`dump(number_format( $this->detailProductItem->getRating(), 1 ));`
returned 8.0 

In template 8.0/5

 Is it conceived or is it a bug?

**Comment by aimeos** [comment]
This has been fixed today in aimeos/ai-controller-frontend:2020.10.x-dev

**Comment by Dinver** [comment]
> This has been fixed today in aimeos/ai-controller-frontend:2020.10.x-dev

Updated today:
"aimeos/ai-client-html": "2020.10.x-dev"
"aimeos/ai-controller-frontend": "2020.10.x-dev"
"aimeos/aimeos-laravel": "2020.10.x-dev"

there is a bug

**Comment by aimeos** [comment]
The product ratings are only updated if you add a new review.

**Comment by Dinver** [comment]
> The product ratings are only updated if you add a new review.

I add review, rating 12.0/5.

**Comment by aimeos** [comment]
The problem also occured in the admin backend and is fixed now in 2020.10.x-dev:
https://github.com/aimeos/ai-admin-jqadm/commit/9d7b20afccc73462c2d7431f7589c475d866aef7

**Comment by Dinver** [comment]
> The problem also occured in the admin backend and is fixed now in 2020.10.x-dev:
> [aimeos/ai-admin-jqadm@9d7b20a](https://github.com/aimeos/ai-admin-jqadm/commit/9d7b20afccc73462c2d7431f7589c475d866aef7)

Now it works, thanks!
