### ISSUE TITLE
[Feature] extend "salutation" options with "divers"

### ISSUE THREAD

**Issue by rowild** [aimeos/ai-client-html#105]
Meanwhile most countries have incorporated a 3rd gender salutation.
Even though it is possible in aimeos to somehow implement this option, it should be provided out-of-the box IMO.

**Comment by aimeos** [comment]
Aimeos offers the "unknown" salutation (value: "") for that

**Comment by rowild** [comment]
But that causes troubles in TYPO3 where an empty string is not valid:
```
checkout {
      standard.address.billing.salutations {
            0 = mr
            1 = mrs
            # unknown
            2 =
          }
```

And translation does not seem to work. E.g. translating "miss":

// de.po in "public/typo3conf/ext/theme/Resources/Private/Extensions/aimeos/client/i18n/de.po"
msgid "miss"
msgstr "Divers"

// terminal:
msgfmt --statistics -c -o de de.po

does not render "divers" in frontend (neither in checkout not in account/address settings).

Furthermore, configuration for the profile section (logged-in customer, edit addresses) seems to be hardcoded:
https://github.com/aimeos/ai-client-html/blob/2655912b0de1353eda0a9f20ed707e1d7674cedf/client/html/src/Client/Html/Account/Profile/Address/Standard.php#L277
and it seems that there are no individual configuration options available for that:
https://aimeos.org/docs/2020.x/config/client-html/account-profile/

If I am misunderstanding something here, I apologise, but would still like to know what else to do in order to display "divers" as a salutation option.

Thank you!

**Comment by aimeos** [comment]
The salutations in the account/history component wasn't translatable up to now and it's changed in this commit: https://github.com/aimeos/ai-client-html/commit/6dd487c79ad0ba4aefa35c03e022086e8beb8f04
Also, the empty value has been added by default to the list of options.

Aimeos doesn't store the gender (male, female, other) of a customer but only salutations (none, company, mr, mrs, miss), so "other" ("divers") is not something you should add. It's better to configure the none value (empty string) in a PHP configuration file to avoid the TypoScript problem. Then, you will also get "Dear test user" as salutation in e-mails, with is gender neutral.

**Comment by aimeos** [comment]
Salutations are now configurable in account/profile too in 2020.10: https://github.com/aimeos/ai-client-html/commit/32bf8ba8930dc4b71c0202951d231e65244243c4
