### ISSUE TITLE
Product links in emails

### ISSUE THREAD

**Issue by jonaseberle** [aimeos/ai-client-html#106]
I am getting 
```
Error while trying to send payment e-mail for order ID "54" and status "5": Parameter "ai__d_name" for route "enhancer_000000001018d7470000000021161855" must match "[^/]++" ("
<span>Bellow</span>
 V6-269" given)
```
Shouldn't it be `'d_name' => $product->getUrl()` instead of `getName()` here since it is used for URL generation?

https://github.com/aimeos/ai-client-html/blob/df5ba0e7ddf4eb61b333903392fdba9b1ed9a54e/client/html/templates/email/payment/html-body-standard.php#L133

**Comment by aimeos** [comment]
It should be `'d_name' => $product->getName( 'url' )`:
https://github.com/aimeos/aimeos-core/blob/master/lib/mshoplib/src/MShop/Product/Item/Standard.php#L235-L242
Can you please create a PR fixing the issue? Maybe there are other occurences where it's wrong.
