### ISSUE TITLE
<p> cannot contain block-level elements

### ISSUE THREAD

**Issue by xerc** [aimeos/ai-client-html#111]
https://github.com/aimeos/ai-client-html/blob/a974deaa74c6f70069f088f37237420620e525de/client/html/templates/catalog/detail/body-standard.php#L126
ref. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p

**Comment by aimeos** [comment]
You are right, can you please create a PR changing it to a `<div>`?

**Comment by aimeos** [comment]
Fixed in https://github.com/aimeos/ai-client-html/commit/e13b3e12810d58d77923de5e2f8053c084f5faa5
