### ISSUE TITLE
close OVERLAY if clicked

### ISSUE THREAD

**Issue by xerc** [aimeos/ai-client-html#112]
https://github.com/aimeos/ai-client-html/blob/6029007a41a05c7c72b87a3c311aa089004e5e04/client/html/themes/aimeos.js#L95
@ CLICK [ .aimeos-container | .aimeos-overlay ]

**Comment by aimeos** [comment]
Can you please elaborate this a bit more so we know what you mean?

**Comment by xerc** [comment]
click @ AddToBasked =>> OVERLAY can only be closed via "X" or ESC

**Comment by aimeos** [comment]
Can you create a PR with the change you would like to add?

**Comment by aimeos** [comment]
Added now: https://github.com/aimeos/ai-client-html/commit/5af0fd5ed4aeef9b58d43ffd05764763e02558ca
