### ISSUE TITLE
<link> should only be used in <head>

### ISSUE THREAD

**Issue by xerc** [aimeos/ai-client-html#115]
ref. https://html.spec.whatwg.org/multipage/links.html#body-ok
https://github.com/aimeos/ai-client-html/blob/c0e888cb97e6d5630bd5a541aa82eb05f3726827/client/html/templates/catalog/stock/body-standard.php#L110

**Comment by aimeos** [comment]
Fixed in https://github.com/aimeos/ai-client-html/commit/6b9f9d7d6319f04ceae21ebe7eeb1224dd7cd56a
