### ISSUE TITLE
image should include nonPreview quality

### ISSUE THREAD

**Issue by xerc** [aimeos/ai-client-html#120]
https://github.com/aimeos/ai-client-html/blob/f6999bf95e5b16917f6deec1ccfcde5de73b3092/lib/custom/src/MW/View/Helper/Image/Standard.php#L47

**Comment by aimeos** [comment]
Then, the parameter `true` must be passed to `getPreview()`

**Comment by xerc** [comment]
https://github.com/aimeos/ai-client-html/blob/master/client/html/templates/catalog/detail/image-partial-standard.php#L29

**Comment by aimeos** [comment]
Is that relevant somewhere? More than 96% of the users use browsers understanding the srcset attribute and they will never use the image in the src attribute: https://caniuse.com/srcset

**Comment by aimeos** [comment]
No feedback
