### ISSUE TITLE
duplicate ID @ detail image

### ISSUE THREAD

**Issue by xerc** [aimeos/ai-client-html#124]
https://github.com/aimeos/ai-client-html/blob/master/client/html/templates/catalog/detail/image-partial-standard.php#L28

**Comment by aimeos** [comment]
The ID attribute shouldn't be duplicate because the ID of each media item is unique. Is the same image added twice for some reason?

**Comment by xerc** [comment]
id="image-50458" @ https://laravel.demo.aimeos.org/default/en/EUR/Demo-voucher/3

**Comment by aimeos** [comment]
The "id" attribute in the image view helper also adds the same ID, which isn't correct.
It would be better to use another prefix here like "img-". Can you create a PR for the necessary change?

**Comment by xerc** [comment]
beforehand; is an ID inevitable?

**Comment by aimeos** [comment]
The ID for the <img> tag is not really necessary, but for the <div> container it's required.

**Comment by aimeos** [comment]
Has been fixed in 2021.07.x
