### ISSUE TITLE
wrong possition if "Company" @ email/pdf

### ISSUE THREAD

**Issue by xerc** [aimeos/ai-client-html#126]
https://github.com/aimeos/ai-client-html/blob/master/client/html/templates/email/payment/pdf-body-standard.php#L123
https://github.com/aimeos/ai-client-html/blob/master/client/html/templates/email/common/html-summary-partial.mjml#L28
https://github.com/aimeos/ai-client-html/blob/master/client/html/templates/email/common/html-summary-partial.mjml#L77

`Firma VName NName`

**Comment by aimeos** [comment]
What do you mean? Can you please explain what's the problem?

**Comment by xerc** [comment]
CORRECT `Herr|Frau VName NName`
WRONG `Firma VName NName`

**Comment by xerc** [comment]
https://github.com/aimeos/ai-client-html/commit/0c14bbc926c5a1eaf59fd43a412062822c7bdd2f

**Comment by xerc** [comment]
still within the PDF
