### ISSUE TITLE
better to show "Add To Basket" when product attributes selected by customer.

### ISSUE THREAD

**Issue by switch-cheehau** [aimeos/ai-client-html#134]
Hi, i'm using version 2021.04

Current behaviour:
- Setup a <kbd>product A</kbd> with type <kbd>selection</kbd> with multiple variants <kbd>product A-1</kbd> and <kbd>product A-2</kbd>.
- Configure <kbd>product A</kbd> **without** price, with categories
- Configure <kbd>product A-1</kbd> and <kbd>product A-2</kbd> properly with prices, without categories.

Result:
Before select attribute, "Add To Basket" button not appear
![image](https://user-images.githubusercontent.com/82187386/119996111-ea65b880-c000-11eb-91fc-7d97bb569003.png)

After select attribute, "Add To Basket" button not appear as well
![image](https://user-images.githubusercontent.com/82187386/119996189-036e6980-c001-11eb-9f6c-383972feb744.png)

Apparently <kbd>product A</kbd> is required to set price in order to work.

I personally feel if <kbd>product A</kbd> is **type:selection**, then should not set any price, but after you select the attributes, it will display the price accordingly, and able to add to basket.

I hope it make sense.

**Comment by aimeos** [comment]
Makes sense to show the button if a variant is selected. The only thing is that you can't sort the product list by price if the selection products have no price associated. Also, if the selection product has a price, the variants don't need one.

**Comment by switch-cheehau** [comment]
I see, understand that the price is needed for sorting.

Considering this:
<kbd>product A</kbd> is a phone offering different capacity and different price
So the setup  i'm trying to do is 
- <kbd>product A</kbd>, type:selection
- <kbd>product A-1</kbd>, type:article, SKU: SKU001, attribute: 8G, price:1000
- <kbd>product A-2</kbd>, type:article, SKU: SKU002, attribute: 16G, price:1500

Currently the workaround is i set a minimum price of that <kbd>product A</kbd>, type:selection

The drawback is customer might click "Add to basket" without selecting any attributes, they will see following error message.
![image](https://user-images.githubusercontent.com/82187386/120050803-adc1ad80-c050-11eb-9e3f-a0c5fc7c1da2.png)

I feel It would be nice for customer if the "Add to basket" is disabled or hidden if attributes not selected properly.

**Comment by aimeos** [comment]
> I feel It would be nice for customer if the "Add to basket" is disabled or hidden if attributes not selected properly.

Yes, that would be perfekt. Are you able to create a pull request with the necessary changes?

**Comment by switch-cheehau** [comment]
yes, i can do but currently i'm still learning the style of coding. i'll be thankful if you able to give me some guidance which related files to modify:)

is the changes related to AimeosCatalog.setupVariantCheck ?

**Comment by aimeos** [comment]
Yes, that should be the right place.

**Comment by switch-cheehau** [comment]
Hi, it might be a stupid question, how do i get the latest changes to my existing project?

I did composer update, but the files in ext/ai-client-html does not update.

**Comment by switch-cheehau** [comment]
> Hi, it might be a stupid question, how do i get the latest changes to my existing project?
> 
> I did composer update, but the files in ext/ai-client-html does not update.

Never mind, found the solution, remove the folder ext/ai-client-html and run composer update again. Thanks!
