### ISSUE TITLE
Locale / currency in navbar

### ISSUE THREAD

**Issue by Weldeasy** [aimeos/ai-client-html#137]
Hello everyone! 

I'm using aimeos to build an ecommerce and currently I'm adapting the templates to the client's needs.

I have a question about the locale/select and currency/select.

I see that only the locale is declared:

![imagen](https://user-images.githubusercontent.com/7500875/120099916-5bf75100-c13e-11eb-8ec7-0c03ed74a0f6.png)

But in the page actually shows both: locale and currency. 

I've digged through the code but I don't see where is this happening.

The problem is that i would like to split them into individual elements.

Thank you very much!

**Comment by aimeos** [comment]
The locale select templates itself contains two sections which you can adapt for a different layout:
https://github.com/aimeos/ai-client-html/tree/master/client/html/templates/locale/select
