### ISSUE TITLE
setupSelectionContent jquery selector issue ".select-option:checked"

### ISSUE THREAD

**Issue by switch-cheehau** [aimeos/ai-client-html#139]
Hi Aimeos,

Please check if it's an issue.

Refering to update in c9bba8244cc57bce69628157191bba587b18ca77

<code>
$(".select-option:checked", event.delegateTarget)
</code>

the selector in setupSelectionContent does not work.

![image](https://user-images.githubusercontent.com/82187386/124357471-261e1e80-dc4e-11eb-850f-6f5f56b7b938.png)

**Comment by aimeos** [comment]
Yes, that might be an issue. Do you have a fix?
The change in the commit was made because the ID of the nodes were not unique and that's required by HTML.

**Comment by switch-cheehau** [comment]
Understand that the id of nodes need to be unique.

But does it require for a class to be unique?
https://github.com/aimeos/ai-client-html/blob/f3cf8b64eb15f05b0fe5f0c753e9c6855ecc7b9e/client/html/templates/common/partials/selection-standard.php#L169-L175

I just change the class <code>select-*-option</code> back to <code>select-option</code>, and it works.
I'm not sure what's the impact if the class not unique.

if the class has to be unique, then we have to change the jquery selector to look for pattern <code>select-*-option</code>

**Comment by aimeos** [comment]
No, the class shouldn't be unique. Can you create a PR with the necessary changes?
