### ISSUE TITLE
Payment text email doesn't render price 

### ISSUE THREAD

**Issue by exemplari** [aimeos/ai-client-html#149]
The HTML email looks fine but the Text version was missing the price. I needed to pass an argument along these templates to render correctly.

client/html/templates/email/payment/text-body-standard.php

https://github.com/aimeos/ai-client-html/blob/2411c7817488b147d6023fae4baf60b13be6acf2/client/html/templates/email/payment/text-body-standard.php#L45

+
'priceFormat' => $this->get( 'priceFormat', '%2$s %1$s' )

**Comment by aimeos** [comment]
Can you create a PR for the required change?

**Comment by aimeos** [comment]
Fixed in https://github.com/aimeos/ai-client-html/commit/59fec65949114c08c8dc34d7fed2aaaf5643f128
