### ISSUE TITLE
Customer receive voucher email with zero amount after redeem voucher code

### ISSUE THREAD

**Issue by switch-cheehau** [aimeos/ai-client-html#154]
Hi Aimeos.

I'm trying to utilise the function of voucher but i encounter this issue, i'm using version 2021-07.
Steps to reproduce
1. Customer purchase a voucher from website and receive the email with voucher code.
2. When customer redeem the voucher, they will receive another new voucher code with amount zero.

I think it's something to do with the codes below
https://github.com/aimeos/ai-client-html/blob/80241881a6533f6109ad38d647986ff8fccf2e1c/controller/jobs/src/Controller/Jobs/Order/Email/Voucher/Standard.php#L106-L111

Does it make sense to trigger the process only when the product voucher price is more than 0?
```
 $expr = array( 
 	$orderSearch->compare( '>=', 'order.mtime', $limitDate ), 
 	$orderSearch->compare( '==', 'order.statuspayment', $status ), 
 	$orderSearch->compare( '==', 'order.base.product.type', 'voucher' ), 
        $orderSearch->compare( '>', 'order.base.product.price', 0 ),
 	$orderSearch->compare( '==', $orderFunc, 0 ), 
 ); 
```

**Comment by aimeos** [comment]
They should not receive a second a second e-mail with a new voucher code at all because the first voucher code is valid as long as it's not redeemed completely. This record in the mshop_order_status table prevents that:
https://github.com/aimeos/ai-client-html/blob/80241881a6533f6109ad38d647986ff8fccf2e1c/controller/jobs/src/Controller/Jobs/Order/Email/Voucher/Standard.php#L103-L104

Is that missing for some reasons?

**Comment by switch-cheehau** [comment]
The first email is sent once and the mshop_order_status table is working fine.

The problem is during redemption of the voucher, it create a line in mshop_order_base_product with negative value.
So when the jobs order/email/voucher execute, it detect that line, create new voucher and email again.

Example:
![image](https://user-images.githubusercontent.com/82187386/132314682-e7b02aad-8f32-44c2-bf98-06e1e538bcb0.png)
baseid 2 is the line when customer purchase voucher

baseid 3 is the lines when customer redeem voucher

**Comment by aimeos** [comment]
Most likely the problem is that in your voucher setup in Marketing > Vouchers > Voucher record, you've used a product of type "Voucher" for "voucher.productcode" instead of a standard article.

**Comment by switch-cheehau** [comment]
I'm so sorry, i mixup with demo-rebate and demo-voucher in the example. I'll close the case
