### ISSUE TITLE
Product URL slug update problem

### ISSUE THREAD

**Issue by nvindice** [aimeos/ai-client-html#167]
We've updated a couple of product labels via CSV product import. The product URL slug did not get changed. Is this on purpose? Is there a way to batch update all URLs?

When adding the product to the basket, this becomes a problem: the `$product` object of type `Order\Item\Base\Product\Standard` object does not return the "url" name but just the default label, compare https://github.com/aimeos/ai-client-html/blob/1103ec08c1f5595a13f4dc56a500d3d85f16692d/client/html/templates/common/summary/detail-standard.php#L190

What is the best solution here?

For the meantime I just removed the `array_diff_key()` on the parameters to preserve the product id in the URL.

**Comment by aimeos** [comment]
The URL slug does only change if you update it manually or via importing a new slug via the CSV files.
Guess, removing the `array_diff_key()` is the best solution and we will merge it into the core if you create a PR.

**Comment by nvindice** [comment]
Thank you for the reply. 

Sorry, I did not make myself very clear, the `array_diff_key()` is not part of the default summy template, but of our own implementation. There is no need to do anything about it if not changing the slug is desired behaviour.
