### ISSUE TITLE
basket-add A non-recoverable error occured

### ISSUE THREAD

**Issue by Cyber-Devs** [aimeos/ai-client-html#172]
After update 'Missing required parameter for [Route: aimeos_shop_detail] [URI: shop/d_name/d_pos?/d_prodid?] [Missing parameter: d_name]' . Error arise along with fs-theme update from contextSite to contextSiteTheme, when use contextSite its work but when change to contextSiteTheme then file missing (js,css).

**Comment by aimeos** [comment]
Can you please execute:
```
composer up
php artisan aimeos:setup
```
This should fix the missing CSS/JS files.

**Comment by Cyber-Devs** [comment]
laravel8.x,aimeos:dev-master, mac,win,linx,
fs-theme solved with aimeos:setup but the basket**A non-recoverable error occured ** is still there. after testing in diffrent OS have the same responce, admin log **'Missing required parameter for [Route: aimeos_shop_detail] [URI: shop/d_name/d_pos?/d_prodid?] [Missing parameter: d_name]' **

**Comment by Cyber-Devs** [comment]
whenever i change the backet ->Stander.php to olde version then everything working without any exception, but new update of the file error, **basket/Standard/Standard.php**

**Comment by aimeos** [comment]
Can you post the stack trace of the error from the logs?

**Comment by aimeos** [comment]
Fixed with commit 6f060cea
