### ISSUE TITLE
Custom Delivery Provider - Label for attribute is not used on front end?

### ISSUE THREAD

**Issue by woodwardmatt** [aimeos/ai-client-html#175]
I'm currently creating a new delivery provider by following the instructions over at: https://aimeos.org/docs/latest/providers/service/

I've noticed that when I add an attribute to be captured on the front end, the label for the field is the not what is being set in the label property

```
private $feconfig = [
    'myprovider.username' => [
        'code' => 'myprovider.username',
        'internalcode' => 'myprovider.username',
        'label' => 'Username',  //This is not used for the label of the attribute on the front end
        'type' => 'string',
        'internaltype' => 'string',
        'default' => '',
        'required' => true,
    ],
];
```

Bug maybe?

- Code Ref: https://github.com/aimeos/ai-client-html/blob/555152f8142aef0dab6e3ffcf6eda460546eff30/templates/client/html/checkout/standard/serviceattr-partial.php#L52

**Comment by aimeos** [comment]
Labels can't be translated so Aimeos uses the code like you already noticed. You can add a translation for your new field like this (Laravel `config/shop.php` example):
```php
'i18n' => [
  'en' => [
    'client/code' => [
      'myprovider.username' => ['User name']
    ]
  ]
]
```

**Comment by woodwardmatt** [comment]
Thank you for that! I can see that's now working - could I request this gets added to the docs at https://aimeos.org/docs/2021.x/providers/service/#add-configuration I think others would find that helpful?

**Comment by aimeos** [comment]
Yes, that's a good idea! Are you able to create a PR with a few sentences explaining it here?
https://github.com/aimeos/aimeos-docs/blob/master/src/providers/service/index.md#add-configuration

**Comment by woodwardmatt** [comment]
Done! :)
