### ISSUE TITLE
Template not available: catalog/lists/items-grid-- postgresql

### ISSUE THREAD

**Issue by MahmoudDevo** [aimeos/ai-client-html#177]
```
Hi,
I use :
PostgreSQL 14
"laravel/framework": "^9.2",
 

  "php": "^7.3|^8.0",
        "aimeos/aimeos-laravel": "~2022.04",
        "aimeos/ai-cms-grapesjs": "2022.04.1",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^9.2",
        "laravel/jetstream": "^2.2",
        "laravel/sanctum": "^2.6",
        "laravel/tinker": "^2.5",
        "livewire/livewire": "^2.0",
        "phing/phing": "^2.16"
```

ERROR
Template not available: catalog/lists/items-grid
#0 C:\laragon\www\site\vendor\aimeos\aimeos-base\src\View\Helper\Partial\Standard.php(36): Aimeos\Base\View\Standard->render('catalog/lists/i...')
aimeos/aimeos-core#1 [internal function]: Aimeos\Base\View\Helper\Partial\Standard->transform('catalog/lists/i...', Array) ...

**Comment by aimeos** [comment]
Thanks for reporting!
The problem has been fixed in 2022.04.x-dev and will be part of the next release.
