### ISSUE TITLE
Basket modal not showing content properly

### ISSUE THREAD

**Issue by pamirsawar** [aimeos/ai-client-html#189]
Issue happens I try to add a new product to the basket. Some of the labels and values are getting overwritten by some function.

![Screenshot_19](https://user-images.githubusercontent.com/53907015/186082189-55cc0ed9-b88a-4542-828d-6b9fbe15d4eb.png)
 
Ai-client-html version: 2022.07.*
windows10
aimeos-laravel: 2022.07.2

**Comment by pamirsawar** [comment]
I believe it's happening because updateBasket function in basket-mini.js. 
jquery selecting classes should be specific to the basket mini component.

**Comment by aimeos** [comment]
Do you have a new installation or updated from an older one?
If it's new, can you check where the problem is rooted?
https://github.com/aimeos/ai-client-html/blob/master/themes/client/html/default/basket-mini.js
