### ISSUE TITLE
More options for Emails

### ISSUE THREAD

**Issue by gilbertsoft** [aimeos/ai-client-html#19]
Would be nice to have more options in the emails, means adding a additional text for a payment type. Think could easy be achieved by a new text type for services (e.g. email short) and so texts can added at the BE. We need this e.g. for payments in advance to get the bank account number to the mails.

**Comment by aimeos** [comment]
Sure, you can always create a new text type, associate it to a service and print it in the e-mail. That's totally up to you.

**Comment by gilbertsoft** [comment]
I'm working on a new subclient doing that.
