### ISSUE TITLE
Category pages are slow

### ISSUE THREAD

**Issue by ARA1985** [aimeos/ai-client-html#190]
https://github.com/aimeos/ai-client-html/blob/ca80030305f7a1eb8b4820e4bb269c93d3a8dc85/client/html/src/Client/Html/Catalog/Lists/Standard.php#L722

The $domains variable is not suitable for use in this request. Because of this request, a lot of memory is used and it takes a long time to load if the store has about 1000 products.

**Comment by aimeos** [comment]
You can restrict the fetched domains if you have a lot of attributes for example using one of these settings:
https://github.com/aimeos/ai-client-html/blob/ca80030305f7a1eb8b4820e4bb269c93d3a8dc85/client/html/src/Client/Html/Catalog/Lists/Standard.php#L480-L535

**Comment by ARA1985** [comment]
This setting is further used to select products on the category page. I can't remove the "product" parameter from it.

**Comment by aimeos** [comment]
I've marked two settings, the second one is for the catalog/lists only:
https://github.com/aimeos/ai-client-html/blob/ca80030305f7a1eb8b4820e4bb269c93d3a8dc85/client/html/src/Client/Html/Catalog/Lists/Standard.php#L506-L535

**Comment by ARA1985** [comment]
Thank you. A good idea.
