### ISSUE TITLE
Product availability

### ISSUE THREAD

**Issue by gilbertsoft** [aimeos/ai-client-html#20]
On some products the green availability square isn't shown. The stock of every product is set to null, I can't see any differences between products showing the square or not. Any idea?

**Comment by aimeos** [comment]
The stock for all products is requested (link is OK) but only for 18 products there's something returned. Can you check if all parameters are available and how much is returned in this method?

https://github.com/aimeos/ai-client-html/blob/master/client/html/src/Client/Html/Catalog/Stock/Standard.php#L292

**Comment by gilbertsoft** [comment]
I think it has to do with the bug on stock change you corrected yesterday. As I saw there were debits made on selections or more accurate a inserts with stock null on it. I did not insert stock data for selections, only for each variant under a selection. But if there's no stock on the selection, the green square is not shown. Why do I need stock on the selection when I only allow to put variants to the basket (client/html/basket/require-variant = 1)?

**Comment by aimeos** [comment]
If you don't add stock levels for the selection products, none are shown in the list view because whose article stock levels should be shown?

As soon as an article of a selection product is bought, a stock level for this selection product is inserted of none exists yet. This is what you mean what we've change yesterday.

**Comment by gilbertsoft** [comment]
The stock of the variants of the selection could be shown.

No, before your change I had errors on bought selections which someone already bought before and the exception was raised because of a sql insert on already existing row in stock. That was the in the exception message and the product in this case is a selection (real products only has numbers in the code, selections names):

INSERT INTO "mshop_stock" (
"productcode", "siteid", "typeid", "stocklevel", "backdate",
"mtime", "editor", "ctime"
) VALUES (
'fb-b-einfach', 1, 1, NULL, NULL, '2017-02-15 00:05:28', '', '2017-02-15 00:05:28'
)

**Comment by gilbertsoft** [comment]
If you have a selection with stock and none of the variants has stock the green square will be shown but the customer can't order at the detail page after selecting a variant because there's no stock.

**Comment by aimeos** [comment]
Therefore, we would have to fetch all variant articles and their stock which we don't do for performance reasons. The stock level of the selection is automatically decreased resp. recalculated if one of the articles is sold. That's in the method we've fixed.

You only need to add a stock level for the selection products once. They are then recalculated automatically. If no stock level for a selection product is available, it will be inserted after one of its articles is sold.

**Comment by gilbertsoft** [comment]
Ok, I already added the stock. Thx!
