### ISSUE TITLE
Filter attributes bug

### ISSUE THREAD

**Issue by Tantacula** [aimeos/ai-client-html#200]
I've created a product with type "selection" and add variants for different sizes. One of variants should have two sizes, previously it was saved with one size attribute and later second size attribute was added (via "variants - variant attributes"), but after saving new attribute didn't appear in filters section. If I swap the attributes in places it will appear in filters after saving.

client/html/catalog/filter/cache is set to false.

Laravel 9.43
PHP 8.1
 "aimeos/ai-client-html": "2022.10.x-dev"

**Comment by aimeos** [comment]
You can add two variant attributes of the same type for a variant article because each one must have exactly one variant attribute per type so the article can be uniquely identified by the variant attributes. Instead, create two variant articles with one size each.

**Comment by Tantacula** [comment]
But the problem with filters still persists. If I swapped variant attributes back, filter still show both attributes, not one of them like before first swapping. Also, if I delete second size from variant it didn't disappears from filters (I have only one product in category with xs, s, lg variants, but filter shows m attribute, which was deleted from one of variants).

**Comment by aimeos** [comment]
Did you remove the variant attribute in the selection product or the variant article in the product panel of the admin backend? The product index needs to be updated and that's the case if your save the selection product. If it doesn't work, check in the database what's exactly stored.

**Comment by Tantacula** [comment]
I go to my selection product -> variants and edit (remove) variant attributes here.

>  The product index needs to be updated and that's the case if your save the selection product.
Are talking about mshop_index_attribute table? Yes, "m size" attribute is here. But it is not present in mshop_product_list

**Comment by aimeos** [comment]
Seems like the mshop_index_attribute table wasn't updated and the attribute removed from there too.
