### ISSUE TITLE
Use double quotes when dynamically loading configurations

### ISSUE THREAD

**Issue by guelzow** [aimeos/ai-client-html#203]
Hi everybody.

The html client base class dynamically loads the template file configuration [here](https://github.com/aimeos/ai-client-html/blob/2022.10.10/src/Client/Html/Base.php#L120) and [here](https://github.com/aimeos/ai-client-html/blob/2022.10.10/src/Client/Html/Base.php#L74).

The variable `$type` should get parsed inside the configuration path, to allow dynamically loading these values. But this only works when using double quotes.

Proposed solution: Use double quotes to allow PHP to parse the string for variables.

Tobi

**Comment by aimeos** [comment]
You are right! Can you create a PR for the necessary change?
