### ISSUE TITLE
just a suggestion about catalog stage/list/... caching

### ISSUE THREAD

**Issue by akropivko** [aimeos/ai-client-html#207]
The catalog caching is on by default - client/html/catalog/stage/cache = 1
It is ok when you know it from the beginning. But it takes some time to catch it if you don't. Because the common practice is to turn on the caching on production, but not to turn off the caching on development.
Probably it would be a good solution either to switch it to 0 bydefault, or to write about this config somewhere in the "Getting started" page of documention. 
Thanks

**Comment by aimeos** [comment]
Our suggestion is to disable caching globally during development using this configuration:
https://github.com/aimeos/aimeos-laravel#hints

**Comment by akropivko** [comment]
But I already HAD this configuratin in my shop.php - 
![Screenshot_14](https://github.com/aimeos/ai-client-html/assets/66216139/560594df-ade4-4c72-be1d-768ed599e7a5)
... and that is why I was confused about what's going on. 
I've checked it once again - the cache on the catalog stage frontend depends from stage/cache only, with the same madmin/cache/manager/name = None 
![Screenshot_15](https://github.com/aimeos/ai-client-html/assets/66216139/3a8b1cf8-954f-46ad-a2f6-62a8820578cb)

**Comment by aimeos** [comment]
We've found the problem and it's now fixed in aimeos/aimeos-laravel dev-master and 2023.07.x-dev
