### ISSUE TITLE
List type (grid / list)

### ISSUE THREAD

**Issue by gilbertsoft** [aimeos/ai-client-html#21]
By clicking on list type link I get a cHash error. Is that a general issue or perhaps dependent from realurl 2.1.5? Hadn't the time for a downgrade now.

**Comment by aimeos** [comment]
No Aimeos links must have a cHash because this always makes problems.
Is this missing in your TS config: https://github.com/aimeos/aimeos-typo3/blob/master/Configuration/TypoScript/setup.txt#L48

**Comment by gilbertsoft** [comment]
No, not missing. My lists page name is "list", but that shoudn,t be the problem I think

**Comment by aimeos** [comment]
No, the page name doesn't matter but you have to find out why the chash value is added despite of the TS config.

**Comment by gilbertsoft** [comment]
I have found it: config is empty at url generation because it's overridden here: https://github.com/aimeos/ai-client-html/blob/master/client/html/templates/catalog/lists/body-default.php#L22

**Comment by gilbertsoft** [comment]
I changed the var to $cconfig and seems to work:

```
foreach( (array) $this->get( 'listCatPath', array() ) as $cat )
{
	$cconfig = $cat->getConfig();
	if( isset( $cconfig['css-class'] ) ) {
		$classes .= ' ' . $cconfig['css-class'];
	}
}
```

**Comment by aimeos** [comment]
Great! Fixed in dev-master now
