### ISSUE TITLE
Undefined array key

### ISSUE THREAD

**Issue by nollm** [aimeos/ai-client-html#219]
I get the exception `PHP Warning: Undefined array key "xyz"` in this line https://github.com/aimeos/ai-client-html/blob/2024.10.1/templates/client/html/common/partials/selection.php#L116 with **PHP 8.2**.
For me it works to check first if the array key is set `<label class="select-name"><?= $enc->html( isset($attrTypes[$code]) ? $attrTypes[$code]->getName() : $this->translate( 'client/code', $code ) ) ?></label>`

**Comment by aimeos** [comment]
Thanks! Can you create a PR with the required change?

**Comment by aimeos** [comment]
Thanks! Can you create a PR with the necessary change?
The same seems to apply here: https://github.com/aimeos/ai-client-html/blob/2024.10.1/templates/client/html/common/partials/attribute.php#L95

The reason for you warning is that you use an attribute type for which no type item has been created or which has been deleted.

**Comment by nollm** [comment]
Of course. I created a pull request for the master branch. Is this the right branch?
