### ISSUE TITLE
Wrong name in email

### ISSUE THREAD

**Issue by gilbertsoft** [aimeos/ai-client-html#22]
We found an other bug today: a customer has made an order and in the first email is my name instead the customers see screenshot. The second email after paying with paypal was correct.

**Comment by aimeos** [comment]
Data must not be cached when generating e-mails:
https://github.com/aimeos/ai-client-html/commit/1dd1380d0b83e2f41ff53d8d621ad4fbb7f554d7

Please delete the screenshot as it contains personal data!

**Comment by gilbertsoft** [comment]
Thanks! Is deleted.

**Comment by gilbertsoft** [comment]
Seems to be ok!

**Comment by aimeos** [comment]
Can you test this package?
https://aimeos.org/fileadmin/download/aimeos_17.2.1-pre1.zip
It should contain all fixes that have been made since the last release

**Comment by gilbertsoft** [comment]
fyi, I'm currently testing with this version on the dev plattform.

**Comment by gilbertsoft** [comment]
So far can't find anything else than #23
