### ISSUE TITLE
Hidden attributes in service are shown

### ISSUE THREAD

**Issue by nollm** [aimeos/ai-client-html#221]
You show hidden attributes from a service here https://github.com/aimeos/ai-client-html/blob/master/templates/client/html/common/summary/service.php#L34
For example hidden payment attributes are shown to the user like response code from bank or something else.
In the past hidden attributes were excluded.

**Comment by aimeos** [comment]
OK, we've reverted the change to the previous behavior

**Comment by nollm** [comment]
Perfect. Thank you!
