### ISSUE TITLE
Printed language in emails

### ISSUE THREAD

**Issue by gilbertsoft** [aimeos/ai-client-html#23]
The language of the customer in emails is not translated, instead the iso code is printed:

Rechnungsadresse
Frau Melanie Müller
Teslastrasse 25 
3151 Musterlingen
Schweiz
de_CH

**Comment by aimeos** [comment]
The `de_CH` language code isn't available in the `client/language` translation files just like any other country specific language code. You can add the translation for your installation in the TS-config field.

**Comment by gilbertsoft** [comment]
Oops, did not add the translation to the scheduler ts config, only to the template. My fault!

But general question on translations: isn't it better to define the translations in a config file, so it's loaded in the frontend and scheduler?

**Comment by aimeos** [comment]
The best way is to create a .po file in your project specific extension and generate the binary MO Gettext file from it. Then it's available everywhere.

**Comment by gilbertsoft** [comment]
Will do so, thanks!
