### ISSUE TITLE
Translations, localization and customers issue

### ISSUE THREAD

**Issue by vmans** [aimeos/ai-client-html#24]
I miss the part that says how customers worldwide read the default sentences in the webshop, and more specifically the checkout, and even more specifically the country select during checkout.

I assume the choosen language in the website is leading?

If that's so, there might be a problem. I translated and improved the Dutch country names. Those names are very different from the English and the original names. Customers might be unable to read it.

It's not enought to adapt ai-client-html/client/i18/country/nl.po as an intermediate solution.

So, is there a more sophisticated approach to customize this whole set?

For instance, TYPO3 has static_info_tables and translated versions of it (base is https://typo3.org/extensions/repository/view/static_info_tables) which makes it possible to customize localization in detail. This goes into further detail even for country zones.

**Comment by aimeos** [comment]
Yes, the language chosen by the customer will be the base of the Aimeos translations shown.

But I don't understand your problem. If customers have chosen English, they will see the Englisch country names. If they've chosen Dutch, all country names are displayed in Dutch, so customers see what they are used to.

**Comment by vmans** [comment]
Consider it a feature request.

In TYPO3 I can configure it like this:
- show country names in the country's language

or like this:
- show country names in the website language

See the difference? Example, cn_short_local and cn_short_en and cn_short_nl:

- 'الإمارات العربيّة المتّحدة' and 'United Arab Emirates' and 'Verenigde Arabische Emiraten'
- 'Հայաստան' and 'Armenia' and 'Armenië'
- 'Azərbaycan' and 'Azerbaijan' and 'Azerbeidzjan'
- 'BiH/БиХ' and 'Bosnia and Herzegovina' and 'Bosnië en Herzegovina'
- 'বাংলাদেশ' and 'Bangladesh' and 'Bangladesh'

So if my English or Dutch website is configured as "show country names in the country's language" than the cn_short_local is used in stead of the other (cn_short_en or cn_short_nl).

And they all revert back to the cn_iso_2 code, so it works elegantly (and much more other local country data until details).

Anyway, now I can do nothing at all. Because I depend on the code base from Aimeos. So I have to do with "NL" in stead of "Nederland" or "Netherlands" despite my translations I have added to www.transifex.com/aimeos/.

**Comment by aimeos** [comment]
OK, understood but if you show the country name in the country language, that won't be understood by most people. The only exception might be people who use the English web site because there's no specific version for their language. On the other side, if they understand English enough to buy on an English web site, they will know their English country name too ... so the value of country names in the countries language is very limited.

If you need your translations immediately, you can always check out the dev-master branch yourself and run `composer update`

**Comment by vmans** [comment]
I understand and it's both ways. It's for a finishing touch. But at least I need it for consistency.

You see it more often. I guess ginving respect to the customers, gives higher conversion and returning customers.

And people might buy still, because they already know what they buy. For instance by a shared link. Or images, downloads, access or tickets.

**Comment by aimeos** [comment]
If you are able to compile a list of country codes in the language of the country, we will add it as additional  configuration possibility.

**Comment by vmans** [comment]
I've sent one by email just a minute ago.

**Comment by aimeos** [comment]
Here are the necessary files and documentation:
https://aimeos.org/docs/Developers/Html_frontend/Use_native_language_country_names
