### ISSUE TITLE
Gmail issue with CSS 

### ISSUE THREAD

**Issue by peteracs** [aimeos/ai-client-html#31]
My e-mails were not rendering CSS in Gmail.

After a long hassle, I found out that Gmail doesn't allow the <style> tag inside the <bod>, only inside the <head>

However these files:
ext/ai-client-html/client/html/templates/email/account/html-body-default.php
ext/ai-client-html/client/html/templates/email/delivery/html-body-default.php
ext/ai-client-html/client/html/templates/email/payment/html-body-default.php
ext/ai-client-html/client/html/templates/email/watch/html-body-default.php

have <style> tag inside the <body>
After I moved the <style> tag to the <head> Gmail rendering was correct!
Please check.

**Comment by aimeos** [comment]
Thanks for the hint. Are you able to create a pull request with the necessary changes?

**Comment by aimeos** [comment]
Fixed in https://github.com/aimeos/ai-client-html/pull/32
