### ISSUE TITLE
JavaScript issues (TYPO3, e.g. Firefox 54.0.1; even in t3 Demo shop)

### ISSUE THREAD

**Issue by faerietree** [aimeos/ai-client-html#34]
On HAMAG and Demo shop site: e.g.
http://typo3.demo.aimeos.org/demo/detail/d/10022/Demo_selection_article/1/

Selecting an option does not update the detail view price in realtime.

No feedback (warnings, logs in console, ...).

(NoScript is turned off thus this can not be the culprit.)

This issue was encountered in version 17_4* too.
Is it only my system? Then there is something wrong with my javascript. Else it could be Aimeos.

Reducing JavaScript to a minimum might be wise because it is again and again prone to generating issues. Most things like hide, show or basic animations can be accomplished using CSS3.

**Comment by faerietree** [comment]
From reading the code this might be fixed by 54c3622258ccf8294ffe3b172defa60ede742dec

**Comment by faerietree** [comment]
Btw. JavaScript on MyAccount page also fails for me. Any significant reasons for the JavaScript overlay instead of loading the link directly to the order detail view?

**Comment by aimeos** [comment]
Works pretty well on http://typo3.demo.aimeos.org/my-account/
Do you have any JS error in the browser console?
