### ISSUE TITLE
cache entry based on config and config through TYPO3-plugin

### ISSUE THREAD

**Issue by s-diez** [aimeos/ai-client-html#43]
I'm not sure if it is only a Problem in TYPO3, but in TYPO3 at least there exists a normal workflow to produce the bug.

As far as I understand cache entries of html, for example of the filter, is dependent on the current config but at certain points only parts of the whole config are considered.
The following code gets html for the body of the filter dependent on the config below the path 'client/html/catalog/filter'.
https://github.com/aimeos/ai-client-html/blob/48e3a70fdfc4dc4972c03d3fc35e06ed6cb183de/client/html/src/Client/Html/Catalog/Filter/Standard.php#L132-L134

In Typo3-Plugins you can configure certain config settings inside the individual plugin instance.
In the Catalog-Filter plugin for example you can configure "client.html.catalog.lists.url.target" and this setting is actually used inside of the html body of the filter, but its values are not considered in the cache key. Configure three instances of the Catalog-Filter plugin each with another value for "client.html.catalog.lists.url.target" and all will use the same cache entry, therefore all filter urls but those from the one which generated the entry are not as expected.

**Comment by s-diez** [comment]
Thanks for the fast update. Good to know this normally is considered and seems to only be an edge case.

**Comment by aimeos** [comment]
The problem is a bit different than initially thought. In the plugins you can add settings for different areas like account, basket, etc. and these settings have to be taken into account as well because they can be different in each plugin instance. We tried to fix that in this commit:

https://github.com/aimeos/ai-client-html/commit/acc5e04254399419fdb7ecc12df0d6fa17cae0e1

Can you checkout `"aimeos/ai-client-html": "2018.07.x-dev"` and test if it works now?

**Comment by s-diez** [comment]
Thanks for the fast fix.

>  In the plugins you can add settings for different areas like account, basket, etc. and these settings have to be taken into account as well because they can be different in each plugin instance

Thats what I actually wanted to convey.

> Can you checkout "aimeos/ai-client-html": "2018.07.x-dev" and test if it works now?

In the test case of multiple plugins of the same type with different settings on one page it works.
But there seems to be a new more serious problem now. The type of the controller does not seem to matter anymore. If you request output of a Catalog-List client with the same configuration as a request to the output of a Catalog-Filter client, you will get the same HTML.

**Comment by s-diez** [comment]
Seems to work fine now. But I must say I find it odd to not actually include the type of the current client in the cache key.

**Comment by aimeos** [comment]
Well, now it is included again, e.g. "client/html/catalog/filter":
- https://github.com/aimeos/ai-client-html/blob/master/client/html/src/Client/Html/Catalog/Filter/Standard.php#L132
- https://github.com/aimeos/ai-client-html/blob/master/client/html/src/Client/Html/Base.php#L604

A new aimeos/ai-client-html release has been tagged.
Thanks for your support! :-)
