### ISSUE TITLE
Address data are lost after validation error

### ISSUE THREAD

**Issue by noll1** [aimeos/ai-client-html#51]
**Environment**
1. Version: 18.10.3
2. Integration: TYPO3
3. System: Ubuntu 18.04.1

**Describe the bug**
When I change the billing address and the validation of only one field wasn't successfully all other changes were reverted.
But when I click "new address" and the validation of a field isn't correct all other changes are still there.

**To Reproduce**
1. Go to address checkout page
2. Change something and leave a required field empty.
3. Click next.
4. All changes are reverted to old values.

**Expected behavior**
Same behaviour like new address. When a validation wasn't correct all other changes should be still there.

**Screenshots**
The salutation was forgotten after changing the address.
![address](https://user-images.githubusercontent.com/42864489/50223875-a59fb700-039c-11e9-9bbc-40a40d6e9a99.png)

**Additional context**
When a customer change his billing address and enter something wrong he should do all other changes again after clicking next.

**Comment by aimeos** [comment]
Confirmed. We will see how we can fix that issue

**Comment by aimeos** [comment]
Issue has been fixed in that commit: https://github.com/aimeos/ai-client-html/commit/916d94853138521f2831685a8d2373bac6ff2582
