### ISSUE TITLE
Count in category filter

### ISSUE THREAD

**Issue by noll1** [aimeos/ai-client-html#52]
**Environment**
1. Version: 18.10.3
2. Integration: TYPO3
3. System: Ubuntu 18.04.1

**Describe the bug**
In version 18.10.3 the count for sub categories doesn't work if you're on top categories.

**To Reproduce**
1. Create sub categories below start.
2. Assign products to that sub categories.
3. Click on category start.

**Expected behavior**
I want to see the count for all the categories always.

**Screenshots**
Left in version 18.10.2 and right in version 18.10.3.
![categories](https://user-images.githubusercontent.com/42864489/50271669-b51f0e80-0435-11e9-9767-f702050c3195.png)

**Additional context**
When I use the setting "client/html/catalog/lists/levels = 3" the counts doesn't include the products below. With this setting I expect that the start node counts all available products but the count display only products that explicit assined to start. Is that what it's meant to be?

**Comment by aimeos** [comment]
That's a missing feature in the catalog tree count template:
https://github.com/aimeos/ai-client-html/blob/master/client/html/templates/catalog/count/tree-body-standard.php

The JS code should add the count values of the children to the parent node if `client/html/catalog/lists/levels` is set to "3". Any help is appreciated :-)

**Comment by noll1** [comment]
Ok, thanks for telling me the place to adapt it.

And what is about the bug that the count is missing for sub categories?

**Comment by aimeos** [comment]
Regarding the missing count in the sub-category:
You've probably missed to rebuild the index because adding or changing the products in the catalog panel doesn't update the product index while saving the product in the product panel does.

**Comment by aimeos** [comment]
Implemented in https://github.com/aimeos/ai-client-html/commit/e415a409c61a71511aa4733a6c65df20bc780826 and will be part of 2019.07
