### ISSUE TITLE
E-mails with CSS

### ISSUE THREAD

**Issue by noll1** [aimeos/ai-client-html#53]
When sending e-mails I noticed that many of the e-mail clients do not display them very good.
Some of them can't send to a customer in this styling.
I have 3 examples here:

**Thunderbird**

![thunderbird](https://user-images.githubusercontent.com/42864489/50286213-0394d300-045f-11e9-95fe-15b56bccabf3.png)

**Outlook/GMail**

![other_clients_normal_view](https://user-images.githubusercontent.com/42864489/50286223-0bed0e00-045f-11e9-9a87-80d79f228951.png)

**Outlook (browser view)**

![outlook_browser_view](https://user-images.githubusercontent.com/42864489/50286242-1b6c5700-045f-11e9-8432-a42497596788.png)

In Thunderbird the representation succeeds as it should be.
With Outlook or GMail any CSS styles are missing. Only the HTML tags are interpreted by the client.
If you set the browser view in Outlook you get the overview more or less well displayed but the images are much too large.

I did some research and read very often that inline-styles should be used for e-mails.
Then I have looked at some mails from other shops and could confirm that they do it exactly like that.
In Aimeos the content of a CSS file (email.css) is written between the <style> tags in the <head> of the mail.

Maybe in the future you should see if you also use this way for the email templates in Aimeos.

**Comment by aimeos** [comment]
An alternative might be https://mjml.io/

**Comment by noll1** [comment]
@AndreasA Thank you for sharing your solution here. Your idea sounds exactly like what I'm looking for.
Unfortunately I failed to integrate the CssToInlineStyles library into the class Aimeos\Client\Html\Email\Payment\Html\Standard.
It would be great if you could use some code examples to show how you integrated the library and where you use it.
A minimalist example would be very helpful.

**Comment by AndreasA** [comment]
I didn't do anything fancy when integrating it - thought about doing so in the next version - but just added it to the composer.json require section and added a FE-Helper that takes the content and parses it with CSS Inline styling. That way I was able to override the mail template and just have put it through render block with it.
But I can post the whole Helper and how I used it here too, if it helps

**Comment by noll1** [comment]
It would be great if you could post the view helper with an explanation here.

**Comment by aimeos** [comment]
Improved the situation a bit by adding fixed width for the images so they don't break the layout: https://github.com/aimeos/ai-client-html/commit/1b9a82e1487da3ecd54b89e5df69a284cb6e60b9

**Comment by AndreasA** [comment]
My helper (it isn't perfect yet but it does the job) looks like this:
```
<?php
namespace Aimeos\MW\View\Helper\InlineCssStyle;

use Aimeos\MShop\Common\Item\PropertyRef\Iface as PropertyRef;
use voku\CssToInlineStyles\CssToInlineStyles;
use voku\helper\HtmlDomParser;

class Standard
    extends \Aimeos\MW\View\Helper\Base
    implements Iface
{
    public function transform(string $content = ''): string
    {
        if (!class_exists('voku\CssToInlineStyles\CssToInlineStyles')) {
            return $content;
        }

        $cssToInlineStyles = new CssToInlineStyles($content);
        $cssToInlineStyles->setUseInlineStylesBlock(true);
        $cssToInlineStyles->setCleanup(false);
        $content = $cssToInlineStyles->convert();
        $content = $this->setHeightAndWidthAttributes($content);

        return (string)$content;
    }

    /**
     * @param string $content
     * @return string
     */
    private function setHeightAndWidthAttributes(string $content): string
    {
        $changed = false;
        $dom = HtmlDomParser::str_get_html($content, $libXMLExtraOptions);
        $xPath = new \DOMXPath($dom->getDocument());
        $nodes = $xPath->query('//img[@style]');
        foreach ($nodes as $node) {
            if ($node->hasAttribute('width') && $node->hasAttribute('height')) {
                continue;
            }

            if (!$node->hasAttribute('style')) {
                continue;
            }

            $style = $node->getAttribute('style');
            $styles = explode(';', $style);
            foreach ($styles as $style) {
                list($property, $value) = explode(':', $style);
                if (!isset($property) || !isset($value)) {
                    continue;
                }
                $property = trim($property);
                if (!in_array($property, ['width', 'height', 'max-width', 'max-height'], true)) {
                    continue;
                }

                $value = trim($value);
                $integerValue = (int)str_replace(['px', 'em', 'rem'], ['', '', ''], $value);
                if (strpos($value, 'em') !== false && ($integerValue  . 'em') === $value) {
                    $integerValue *= (int)$this->config( 'client/html/ai-wines/helper/inline-css-style/standard/em-size', 12);
                } elseif (strpos($value, 'rem') !== false && ($integerValue  . 'rem') === $value) {
                    $integerValue *= (int)$this->config( 'client/html/ai-wines/helper/inline-css-style/standard/rem-size', 16);
                } elseif (strpos($value, 'px') === false || ($integerValue  . 'px') !== $value) {
                    continue;
                }

                if (in_array($property, ['width', 'max-width'], true) && !$node->hasAttribute('width')) {
                    $changed = true;
                    $node->setAttribute('width', $integerValue);
                } elseif (in_array($property, ['height', 'max-height'], true) && !$node->hasAttribute('height')) {
                    $changed = true;
                    $node->setAttribute('height', $integerValue);
                }
            }
        }

        if (!$changed) {
            return $content;
        }

        $html = $dom->html();

        return $html;
    }
}

```

And the e-mail tempalte like this:
```
<?php
$enc = $this->encoder();

$title = $this->translate( 'client', 'E-mail notification' );

$fontCss = '';
$fontCssFile = $this->config('client/html/common/template/baseurl', 'client/html/themes/elegance') . '/fonts.woff.css';
if( file_exists( $fontCssFile ) && ( $fontCss = file_get_contents( $fontCssFile ) ) !== false ) {
    $fontCss = '<style type="text/css">'. PHP_EOL
                    . $fontCss . PHP_EOL
                    . 'body.aimeos-email * {' . PHP_EOL
                        . 'font-family: "Web-Font", Arial, sans-serif !important;' . PHP_EOL
                    . '}' . PHP_EOL
                . '</style>' . PHP_EOL;
}

?>
<?php $this->block()->start( 'email/payment/html' ); ?>
<!DOCTYPE html>
<html lang="<?= $this->param('locale', 'de'); ?>">
	<head>
		<title><?= $enc->html( $title, $enc::TRUST ); ?></title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<style type="text/css">
            html, body {
                width: 100%;
            }

            html, body, div, span, applet, object, iframe, h1, h2, h3, h4, h5, h6, p, blockquote, pre,
            a, abbr, acronym, address, big, cite, code, del, dfn, em, img, ins, kbd, q, s, samp,
            small, strike, strong, sub, sup, tt, var, b, u, i, center, dl, dt, dd, ol, ul, li,
            fieldset, form, label, legend, table, caption, tbody, tfoot, thead, tr, th, td,
            article, aside, canvas, details, embed, figure, figcaption, footer, header, hgroup,
            menu, nav, output, ruby, section, summary, time, mark, audio, video {
                margin: 0;
                padding: 0;
                border: 0;
                font-size: 100%;
                font: inherit;
                vertical-align: baseline;
            }
            /* HTML5 display-role reset for older browsers */
            article, aside, details, figcaption, figure, footer, header, hgroup, menu, nav, section {
                display: block;
            }

            <?= $this->get( 'htmlCss' ); ?>

        </style>
	</head>
	<body class="aimeos-email">
		<div class="aimeos">
            CONTENT
		</div>

	</body>
</html>
<?php $this->block()->stop(); ?>
<?= trim(preg_replace('/<\/head>/', ('</head>' . $fontCss), $this->inlineCssStyle($this->block()->get( 'email/payment/html' )), 1)); ?>
```

This includes injecting a font CSS file (where the font is WOFF and it is base64 encoded - WOFF so when using Outlook open in browser that font is used ). 

Probably not necessary but in case you need it which is I replace the closing head tag 
and override the font-famliy --> as Outlook otherwise does not correctly use the fallback font but as outlook ignores the important tag (at least up to 2016 and with 2019 this fallback issue was fixed).

The DOCTYPE and IE=edge tag have both been added so that when the open in browser function of Outlook is used, it uses IE11 rendering and therefore renders the template correctly including font.

**Comment by aimeos** [comment]
We are evaluating different options at the moment. We've already added width to the images so they doesn't screw up the layout any more.

**Comment by AndreasA** [comment]
@aimeos The only issue with adding width in the template is that in order to modify it, one has to override the corresponding template (as CSS alone isn't enough).
However, I guess there is no real other solution regarding this.

**Comment by aimeos** [comment]
The e-mails have been rewritten to use the MJML framework for responsive e-mails. The new layout almost looks the same in all e-mail clients:
![responsive-email](https://user-images.githubusercontent.com/8647429/58623311-fe6d6700-82cd-11e9-8720-e1faacf5246f.png)
