### ISSUE TITLE
[FEATURE] E-Mail salutation - Possibility to be gender specific

### ISSUE THREAD

**Issue by AndreasA** [aimeos/ai-client-html#54]
Currently in the translation for e-mail salutation the format is only "Dear %1$s %2$s %3$s".
 However, it would be good to have a format that can be per gender - it should be optional that way, if it isn't set it should default to the current one.
The reason is that e.g. in German in the polite wording there is a difference between genders and so it requires a gender specific salutation.

**Comment by aimeos** [comment]
Confirmed

**Comment by aimeos** [comment]
Implemented in https://github.com/aimeos/ai-client-html/commit/b4119c9bfa6221ab50135dbadeefe2e1ca0d3a28 and will be part of 2019.07
