### ISSUE TITLE
Coupon error codes

### ISSUE THREAD

**Issue by nvindice** [aimeos/ai-client-html#66]
When a coupon is not available, en error like 'coupon.1234.coupon.gone' is displayed (where _1234_ is the coupon code). Is this desired behaviour? IMO, it would be better to either remove the coupon code from the error message entirely or to parse it via `sprintf()` into the translated error message.

The method `translatePluginErrorCodes()` already removes product codes from the error string: https://github.com/aimeos/ai-client-html/blob/38b02c5c80d28c4bda067584d4dc7734aadd7d80/client/html/src/Client/Html/Base.php#L710

Can I expand this behaviour on coupon codes? I would create a PR for this if you agree.

**Comment by aimeos** [comment]
Yes, makes sense
