### ISSUE TITLE
Empty value for parameter "f_catid" prevents default category

### ISSUE THREAD

**Issue by s-diez** [aimeos/ai-client-html#69]
Hi

Typo3: 8.7.24
Aimeos: 2019.04.4
Ai-Client-HTML: 2019.04.4

When the parameter `f_catid` exists but is empty, the default category is not used.
In previous versions the actual value of `f_catid` is compared to `""`. Now the default category is only used as the default value for the "param" view helper. The helper only checks for existance.
I think the change in behaviour was done here.
https://github.com/aimeos/ai-client-html/commit/1b5b8e68339333f25935f3be81daa7de124b0dfd#diff-6f16179781a98657097155c425017a20

In our setup under some circumstances the parameter can be set to an empty value. In this case we would like the default category. Should I fix the above behaviour in our setup or was the change unintended?

Greetings Sebastian Diez

**Comment by aimeos** [comment]
I think that was unintended and feel free to change it to something like this:
`$params['f_catid'] = $view->param( 'f_catid' ) ?: $context->getConfig()->get( 'client/html/catalog/lists/catid-default' );`

**Comment by s-diez** [comment]
Ok thanks for the fast response as always. I'll provide a pull request tomorrow.
