### ISSUE TITLE
Feature Request: Delivery emails should differentiate items (For instance refused items)

### ISSUE THREAD

**Issue by khalidbashirbajwa** [aimeos/ai-client-html#71]
Is your feature request related to a problem?
We have implemented a shop using Aimeos. In the normal flow customer buys multiple products. Sometimes some of the products in the order are not available. When we change the status of the individual items to refused and then change the delivery status of the order the generated Email doesn't take that into account. The generated Email to customer should differentiate between successful and unsuccessful items

Describe the solution you'd like
Changing the status of individual items should be respected in the generated email for the order and the items should be differentiated

Describe alternatives you've considered
Currently we have to send separate Emails to customers to let them know that these items were not available

Additional context
None

**Comment by aimeos** [comment]
The delivery status is now displayed for each product in the e-mails if it's different from "unfinished". The feature will be part of the next version (2019.07).
