### ISSUE TITLE
Product link in basket list

### ISSUE THREAD

**Issue by DavidHedden** [aimeos/ai-client-html#72]
#
The link in the common/summary/detail-standard seems to be wrong.
In all other Templates it changed to the "name" of the product instead of the ID.
In my case i could solve it by changing it to take the product code as the value for the d_name parameter. But since in the catalog list for example the value is taken with $product->getName('url') i would gues theres more logic to it.

**Comment by aimeos** [comment]
Can you please provide a link to the line that seems to be wrong?

**Comment by DavidHedden** [comment]
https://github.com/aimeos/ai-client-html/blob/1697c980d8c153923cf8a1f712f8c8926ada4a81/client/html/templates/common/summary/detail-standard.php#L205-L212

**Comment by aimeos** [comment]
Unfortunately, it's not possible to use the product name only in this case as the "basket product" doesn't contain the URL segment of the product any more. Using the product name only will fail when used for product lookups. There's currently a change pending that fixes the issue by using the product ID if available and the product URL segment as second choice.

**Comment by DavidHedden** [comment]
Good to know that theres already a fix on the way

**Comment by aimeos** [comment]
The fix is now available in "aimeos/ai-client-html": "2019.04.x-dev":
https://github.com/aimeos/ai-client-html/commits/2019.04
