### ISSUE TITLE
Urgent: Mini basket link broken

### ISSUE THREAD

**Issue by nvindice** [aimeos/ai-client-html#75]
Platform: Typo3 v8.7.26 with RealURL
Aimeos: v2018.10.x-dev
Localization: DE

We have experienced a strange problem on saturday. Our German shop uses localized domains like www.shop.de/warenkorb/ for the basket. On saturday, the mini basket link directed to www.shop.de/basket/ instead, which killed the checkout process for a couple of customers, because they encountered a 404 when trying to access the basket/checkout process.

When clearing the Typo3 frontend cache yesterday, all pages were re-rendered and the problem was gone.

We have no clue why this bug occured, but it has the potential to prevent all orders for a whole weekend, if nobody notices. So we need to resolve the root cause fast.

**Comment by aimeos** [comment]
That seems like one of those RealUrl bugs ...

**Comment by nvindice** [comment]
I don't understand where RealURL should get the word "basket" as a speaking segment from?! It's nowhere in the Typo3 page settings AFAIK.

**Comment by aimeos** [comment]
This is usually the English page name

**Comment by nvindice** [comment]
Yes, but I renamed the page in Typo3 BE to "Warenkorb". So, IMHO, RealURL should have no reason to call it "basket". Or am I missing something?

What about the Aimeos URL helper, does it default to any value if e.g. no target configuration is given?

**Comment by aimeos** [comment]
No, no default values. If you renamed the page in TYPO3 BE, the name may be still in the tx_realurl tables. You should clear those tables to avoid problems.

**Comment by nvindice** [comment]
Well, if no default values are set by Aimeos, it has to be an issue with Typo3 oder RealURL, I guess... I cleared all the tables and will monitor this issue. Thank you.
