### ISSUE TITLE
[BUG] create user account option visible, if email already in used and if user is logged in

### ISSUE THREAD

**Issue by AndreasA** [aimeos/ai-client-html#8]
If a user is logged in or if the email selected is already in use the checkbox regarding the creation of a new user account is still visible.
Of course, the user account is not created but I think the checkbox shouldn't even be visible in this case.

**Comment by aimeos** [comment]
Thanks for spotting! Fixed with https://github.com/aimeos/ai-client-html/commit/4d6e86a95cf332f182ceaad7a9c873a076f32bef

**Comment by AndreasA** [comment]
Great. Thanks. I will update and test it.

**Comment by AndreasA** [comment]
Seems to work great. Thanks again.
