### ISSUE TITLE
Possible bug: Salutation in emails

### ISSUE THREAD

**Issue by nvindice** [aimeos/ai-client-html#80]
Hi Aimeos team,

in https://github.com/aimeos/ai-client-html/blob/ebad09ee0c95ad67e5688467474e68eeb20c5de4/client/html/src/Client/Html/Email/Payment/Standard.php#L518 the translation domain `client/html/email` is used, which seems to be invalid. I have my own implementation of this class, so I can not confirm if the problem exists in the original setup, but at least in my setup this translation results in an error (and unsent emails).

Same for some other Email classes like Delivery, ...

EDIT: Sorry, forgot to mention: Version 2018.x

**Comment by aimeos** [comment]
Thank you for your bug report. It has been fixed in the 2018.10 branch. A new release has been tagged

**Comment by nvindice** [comment]
Thank you - Watch and Account classes seem to be affected, too.

**Comment by aimeos** [comment]
Thanks, fixed too
