### ISSUE TITLE
Infinite Scrolling

### ISSUE THREAD

**Issue by nvindice** [aimeos/ai-client-html#83]
Are you interested in a PR for 2018.x with infinite scrolling at product catalog list?

**Comment by aimeos** [comment]
Sure, but rather for 2019.x. There hasn't been changed much in the frontend so porting should be easy

**Comment by nvindice** [comment]
See #84. Sorry, I have no resources to port this to 2019.x right now...

**Comment by aimeos** [comment]
Done
