### ISSUE TITLE
Optional delivery e-mail results in error during delivery changes

### ISSUE THREAD

**Issue by AndreasA** [aimeos/ai-client-html#9]
If the delivery e-mail is optional, e.g. if a customer wants to send the product to his or her work place, they don't need another e-mail address.

However, in this case the delivery address does exist but there is no e-mail associated with it which results in the notification being unable to be sent.

Therefore, in this case the e-mail of the billing address should be used to send the e-mail notification.
Maybe the easiest solution would be to store the billing e-mail address with the delivery address, if no individual e-mail address is submitted.

**Comment by aimeos** [comment]
Either that or use the payment address here:
https://github.com/aimeos/ai-client-html/blob/master/controller/jobs/src/Controller/Jobs/Order/Email/Delivery/Standard.php#L148

**Comment by AndreasA** [comment]
Using the payment address would result in the wrong address being used in the view.
Optionally, we could set the e-mail temporarily there for the delivery address from the payment address.

**Comment by AndreasA** [comment]
Or maybe here:
https://github.com/aimeos/ai-client-html/blob/master/client/html/src/Client/Html/Email/Delivery/Standard.php#L178

The billing address is retrieved there and the delivery address is already view->extAddressItem
Therefore, if there is no e-mail in view->extAddressItem, we could just use the one from the billing address in regards to addTo and do not execute addCc for the billing address e-mail.

**Comment by aimeos** [comment]
It has been fixed as part of a code refactoring:
https://github.com/aimeos/ai-client-html/blob/master/controller/jobs/src/Controller/Jobs/Order/Email/Delivery/Standard.php#L174
