### ISSUE TITLE
jQuery targets wrong element in account history

### ISSUE THREAD

**Issue by FlorianMoser** [aimeos/ai-client-html#95]
In [ai-client-html/client/html/templates/account/history/list-body-standard.php](https://github.com/aimeos/ai-client-html/blob/master/client/html/templates/account/history/list-body-standard.php#L102), the DIV with class "history-item" has no descending A element.

However in the [default theme JS](https://github.com/aimeos/ai-client-html/blob/master/client/html/themes/aimeos.js#L200) you target a direct A child of .history-item. Either one needs an update.

**Comment by aimeos** [comment]
Thank you for your hint. Can you create a PR with a fix?

**Comment by FlorianMoser** [comment]
Was right on it ;-)

**Comment by aimeos** [comment]
Merged. Thank you for your help :-)
